// ============================================================
// DATA CHECKLIST PM (Preventive Maintenance)
// ------------------------------------------------------------
// Setiap checklist di sini = 1 form terpisah (mirip 1 sheet di
// Excel aslinya), dikelompokkan per kategori equipment biar
// gampang dicari di halaman pm.html.
//
// CARA NAMBAH CHECKLIST BARU:
// 1. Tambah object baru di dalam array "checklists" pada
//    kategori yang sesuai (atau bikin kategori baru).
// 2. "id" harus unik (dipakai di URL: checklist.html?id=...).
// 3. "layout":
//    - "single"       -> kolom Standar + Hasil + Keterangan, satu kali
//                         isi per submit (cocok utk Weekly/Yearly/xxxx Hours).
//    - "monthly-grid" -> tabel 12 kolom (Januari-Desember), satu form
//                         isi 1 tahun sekaligus (cocok utk periode Monthly).
//    - "daily-grid"   -> tabel 7 kolom (Senin-Minggu), satu form isi
//                         1 minggu sekaligus (cocok utk periode Daily).
// 4. "items": daftar No + Uraian pekerjaan + Standar, urut
//    sesuai dokumen aslinya. Sub-item yang di dokumen asli tanpa nomor
//    (misal "Current for: a. Motor  b. Fan") digabung jadi satu baris
//    per sub-item dengan format "Induk - Sub" biar tetap 1 baris = 1 kolom
//    input di grid.
// ============================================================

export const CHECKLIST_CATEGORIES = [
  {
    key: "compressor",
    label: "Compressor",
    checklists: [
      {
        id: "compressor-non-oil-free-weekly",
        title: "Maintenance Compressor Low Pressure Non Oil Free",
        periodeLabel: "Weekly",
        layout: "single",
        items: [
          { no: 1, uraian: "Cleaning Filter Udara", standar: "Bersih" },
          { no: 2, uraian: "Cleaning Oil & Air Cooler", standar: "Bersih" },
          { no: 3, uraian: "Cleaning Kipas Motor", standar: "Bersih" },
          { no: 4, uraian: "Check the cooling oil level", standar: "Medium" },
          { no: 5, uraian: "Check water Trap Compressor", standar: "Normal" },
          { no: 6, uraian: "Check Kebocoran Oil", standar: "Tidak Bocor" },
          { no: 7, uraian: "Check water Trap di Receiver Tank", standar: "Normal" },
          { no: 8, uraian: "Check Pressure Gauge Receiver Tank", standar: "Normal" },
          { no: 9, uraian: "Check Eco drain / water trap Dryer", standar: "Normal" },
          { no: 10, uraian: "Running Hours Terakhir", standar: "" },
        ],
      },
      {
        id: "compressor-oil-free-weekly",
        title: "Maintenance Compressor Low Pressure Oil Free",
        periodeLabel: "Weekly",
        layout: "single",
        items: [
          { no: 1, uraian: "Cleaning Filter Udara", standar: "Bersih" },
          { no: 2, uraian: "Cleaning Air Cooler", standar: "Bersih" },
          { no: 3, uraian: "Cleaning Kipas Motor", standar: "Bersih" },
          { no: 4, uraian: "Check water Trap Compressor", standar: "Normal" },
          { no: 5, uraian: "Check water Trap di Receiver Tank", standar: "Normal" },
          { no: 6, uraian: "Check Pressure Gauge Receiver Tank", standar: "Normal" },
          { no: 7, uraian: "Check Eco drain / water trap Dryer", standar: "Normal" },
          { no: 8, uraian: "Running Hours Terakhir", standar: "" },
        ],
      },
      {
        id: "compressor-non-oil-free-monthly",
        title: "Maintenance Compressor Low Pressure Non Oil Free",
        periodeLabel: "Monthly",
        layout: "monthly-grid",
        items: [
          { no: 1, uraian: "Operation Mode", standar: "AUTO" },
          { no: 2, uraian: "Pressure Switch", standar: "AUTO" },
          { no: 3, uraian: "Loading Pressure Setting", standar: "6.7 Bar" },
          { no: 4, uraian: "Auto Start Pressure Setting", standar: "8.5 Bar" },
          { no: 5, uraian: "Cleaning Filter Udara", standar: "Bersih" },
          { no: 6, uraian: "Cleaning Cooler", standar: "Bersih" },
          { no: 7, uraian: "Cleaning Kipas Motor", standar: "Bersih" },
          { no: 8, uraian: "Periksa Kondisi Oli / Level Oli", standar: "Medium" },
          { no: 9, uraian: "Periksa Drain Trap Compressor", standar: "Normal" },
          { no: 10, uraian: "Periksa Kebocoran Oil", standar: "Tidak Bocor" },
          { no: 11, uraian: "Periksa Motor Fan Cooling Oil dan Udara", standar: "Normal" },
          { no: 12, uraian: "Periksa Noise Compressor", standar: "Tidak Noise" },
          { no: 13, uraian: "Periksa Discharge Temperature", standar: "Max. 100°C" },
          { no: 14, uraian: "Periksa Ambient Temperature", standar: "Max. 45°C" },
          { no: 15, uraian: "Running Hours Terakhir", standar: "Hours" },
          { no: 16, uraian: "Periksa dan Greasing Bearing Motor", standar: "Tidak Berisik" },
          { no: 17, uraian: "Periksa Drain Trap di Receiver Tank", standar: "Normal" },
          { no: 18, uraian: "Periksa Pressure Gauge Receiver Tank", standar: "7-9 Bar" },
          { no: 19, uraian: "Periksa Drain Trap Air Dryer", standar: "Normal" },
          { no: 20, uraian: "Periksa Compressor Refrigerant Air Dryer", standar: "Normal" },
          { no: 21, uraian: "Periksa Filter Input Dryer", standar: "Bersih" },
          { no: 22, uraian: "Periksa Filter Output Dryer", standar: "Bersih" },
          { no: 23, uraian: "Periksa Fungsi Control Panel Compressor", standar: "Normal" },
          { no: 24, uraian: "Periksa Fungsi Control Panel Air Dryer", standar: "Normal" },
          { no: 25, uraian: "Periksa Sensor Temperatur", standar: "Normal" },
          { no: 26, uraian: "Periksa Indikator Dryer", standar: "Normal" },
          { no: 27, uraian: "Periksa Fan Kondensor Air Dryer", standar: "Normal" },
          { no: 28, uraian: "MCCB Compressor Terpasang", standar: "A" },
          { no: 29, uraian: "MCCB Air Dryer Terpasang", standar: "A" },
          { no: 30, uraian: "Voltage Compressor", standar: "380-400 V" },
          { no: 31, uraian: "Voltage Air Dryer", standar: "380-400 V" },
          { no: 32, uraian: "Current Compressor", standar: "A" },
          { no: 33, uraian: "Current Air Dryer", standar: "A" },
        ],
      },
      {
        id: "compressor-oil-free-monthly",
        title: "Maintenance Compressor Low Pressure Oil Free",
        periodeLabel: "Monthly",
        layout: "monthly-grid",
        items: [
          { no: 1, uraian: "Operation Mode", standar: "AUTO" },
          { no: 2, uraian: "Pressure Switch", standar: "AUTO" },
          { no: 3, uraian: "Loading Pressure Setting", standar: "Bar" },
          { no: 4, uraian: "Auto Start Pressure Setting", standar: "Bar" },
          { no: 5, uraian: "Cleaning Filter Udara", standar: "Bersih" },
          { no: 6, uraian: "Cleaning Cooler", standar: "Bersih" },
          { no: 7, uraian: "Cleaning Kipas Motor", standar: "Bersih" },
          { no: 8, uraian: "Periksa Drain Trap Compressor", standar: "Normal" },
          { no: 9, uraian: "Periksa Noise Compressor", standar: "Tidak Noise" },
          { no: 10, uraian: "Periksa Discharge Temperature", standar: "Max. 100°C" },
          { no: 11, uraian: "Periksa Ambient Temperature", standar: "Max. 45°C" },
          { no: 12, uraian: "Running Hours Terakhir", standar: "Hours" },
          { no: 13, uraian: "Periksa dan Greasing Bearing Motor", standar: "Tidak Berisik" },
          { no: 14, uraian: "Periksa Drain Trap di Receiver Tank", standar: "Normal" },
          { no: 15, uraian: "Periksa Pressure Gauge Receiver Tank", standar: "7-9 Bar" },
          { no: 16, uraian: "Periksa Drain Trap Air Dryer", standar: "Normal" },
          { no: 17, uraian: "Periksa Compressor Refrigerant Air Dryer", standar: "Normal" },
          { no: 18, uraian: "Periksa Filter Input Dryer", standar: "Bersih" },
          { no: 19, uraian: "Periksa Filter Output Dryer", standar: "Bersih" },
          { no: 20, uraian: "Periksa Fungsi Control Panel Compressor", standar: "Normal" },
          { no: 21, uraian: "Periksa Fungsi Control Panel Air Dryer", standar: "Normal" },
          { no: 22, uraian: "Periksa Sensor Temperatur", standar: "Normal" },
          { no: 23, uraian: "Periksa Indikator Dryer", standar: "Normal" },
          { no: 24, uraian: "Periksa Fan Kondensor Air Dryer", standar: "Normal" },
          { no: 25, uraian: "MCCB Compressor Terpasang", standar: "A" },
          { no: 26, uraian: "MCCB Air Dryer Terpasang", standar: "A" },
          { no: 27, uraian: "Voltage Compressor", standar: "380-400 V" },
          { no: 28, uraian: "Voltage Air Dryer", standar: "380-400 V" },
          { no: 29, uraian: "Current Compressor", standar: "A" },
          { no: 30, uraian: "Current Air Dryer", standar: "A" },
        ],
      },
      {
        id: "compressor-non-oil-free-yearly",
        title: "Maintenance Compressor Low Pressure Non Oil Free",
        periodeLabel: "Yearly",
        layout: "single",
        items: [
          { no: 1, uraian: "Ambient Temperature", standar: "Max. 45°C" },
          { no: 2, uraian: "Discharge Temperature", standar: "Max. 100°C" },
          { no: 3, uraian: "Discharge Pressure", standar: "8.5 Bar" },
          { no: 4, uraian: "Current (R/S/T)", standar: "A" },
          { no: 5, uraian: "Voltage (R/S/T)", standar: "380-400 V" },
          { no: 6, uraian: "Check For Leaking - Air Line", standar: "Good" },
          { no: 7, uraian: "Check For Leaking - Oil Line", standar: "Good" },
          { no: 8, uraian: "Check For Leaking - Water Line", standar: "Good" },
          { no: 9, uraian: "Check For Servicibility - Gauges", standar: "Normal" },
          { no: 10, uraian: "Check For Servicibility - Instrument Light", standar: "Good" },
          { no: 11, uraian: "Check For Servicibility - Contactor", standar: "Good" },
          { no: 12, uraian: "Winding Resistance - Phase R", standar: "Balance" },
          { no: 13, uraian: "Winding Resistance - Phase S", standar: "" },
          { no: 14, uraian: "Winding Resistance - Phase T", standar: "" },
          { no: 15, uraian: "Insulation Test - Phase R-S", standar: "> 10 Mohm" },
          { no: 16, uraian: "Insulation Test - Phase S-T", standar: "> 10 Mohm" },
          { no: 17, uraian: "Insulation Test - Phase T-R", standar: "> 10 Mohm" },
          { no: 18, uraian: "Insulation Test - Phase R-G", standar: "> 10 Mohm" },
          { no: 19, uraian: "Insulation Test - Phase S-G", standar: "> 10 Mohm" },
          { no: 20, uraian: "Insulation Test - Phase T-G", standar: "> 10 Mohm" },
          { no: 21, uraian: "Change Oil", standar: "Change" },
          { no: 22, uraian: "Change Oil Filter", standar: "Change" },
          { no: 23, uraian: "Change Air Filter", standar: "Change" },
          { no: 24, uraian: "Change Separator Cartridge", standar: "Change" },
          { no: 25, uraian: "Tightening All Bolt and Nut", standar: "Retightening" },
          { no: 26, uraian: "Cable Installation", standar: "Good" },
          { no: 27, uraian: "Main Body", standar: "Good" },
          { no: 28, uraian: "Running Hours", standar: "Hours" },
          { no: 29, uraian: "Periksa kebocoran oil", standar: "Tidak Bocor" },
        ],
      },
      {
        id: "compressor-oil-free-yearly",
        title: "Maintenance Compressor Low Pressure Oil Free",
        periodeLabel: "Yearly",
        layout: "single",
        items: [
          { no: 1, uraian: "Ambient Temperature", standar: "Max. 45°C" },
          { no: 2, uraian: "Discharge Temperature", standar: "Max. 100°C" },
          { no: 3, uraian: "Discharge Pressure", standar: "8.5 Bar" },
          { no: 4, uraian: "Current (R/S/T)", standar: "A" },
          { no: 5, uraian: "Voltage (R/S/T)", standar: "380-400 V" },
          { no: 6, uraian: "Check For Leaking - Air Line", standar: "Good" },
          { no: 7, uraian: "Check For Leaking - Oil Line", standar: "Good" },
          { no: 8, uraian: "Check For Leaking - Water Line", standar: "Good" },
          { no: 9, uraian: "Check For Servicibility - Gauges", standar: "Normal" },
          { no: 10, uraian: "Check For Servicibility - Instrument Light", standar: "Good" },
          { no: 11, uraian: "Check For Servicibility - Contactor", standar: "Good" },
          { no: 12, uraian: "Winding Resistance - Phase R", standar: "Balance" },
          { no: 13, uraian: "Winding Resistance - Phase S", standar: "" },
          { no: 14, uraian: "Winding Resistance - Phase T", standar: "" },
          { no: 15, uraian: "Insulation Test - Phase R-S", standar: "> 10 Mohm" },
          { no: 16, uraian: "Insulation Test - Phase S-T", standar: "> 10 Mohm" },
          { no: 17, uraian: "Insulation Test - Phase T-R", standar: "> 10 Mohm" },
          { no: 18, uraian: "Insulation Test - Phase R-G", standar: "> 10 Mohm" },
          { no: 19, uraian: "Insulation Test - Phase S-G", standar: "> 10 Mohm" },
          { no: 20, uraian: "Insulation Test - Phase T-G", standar: "> 10 Mohm" },
          { no: 21, uraian: "Change Oil", standar: "Change" },
          { no: 22, uraian: "Change Oil Filter", standar: "Change" },
          { no: 23, uraian: "Change Air Filter", standar: "Change" },
          { no: 24, uraian: "Change Separator Cartridge", standar: "Change" },
          { no: 25, uraian: "Tightening All Bolt and Nut", standar: "Retightening" },
          { no: 26, uraian: "Cable Installation", standar: "Good" },
          { no: 27, uraian: "Main Body", standar: "Good" },
          { no: 28, uraian: "Running Hours", standar: "Hours" },
          { no: 29, uraian: "Periksa kebocoran oil", standar: "Tidak Bocor" },
        ],
      },
      {
        id: "compressor-kaeser-2000h",
        title: "Maintenance Compressor Kaeser",
        periodeLabel: "2000 / 3000 Hours",
        layout: "single",
        items: [
          { no: 1, uraian: "Cleaning Air & Oil Cooler", standar: "Bersih" },
          { no: 2, uraian: "Cleaning / Change Filter Mat", standar: "Bersih" },
          { no: 3, uraian: "Check the Leak", standar: "Tidak Bocor" },
          { no: 4, uraian: "Check the Oil Level", standar: "L/M/H" },
          { no: 5, uraian: "Change the Air Filter Cartridge", standar: "OK" },
          { no: 6, uraian: "Change the Oil Filter", standar: "OK" },
          { no: 7, uraian: "Change the Cooling Oil", standar: "OK" },
          { no: 8, uraian: "Check & Cleaning electrical panel", standar: "Bersih" },
          { no: 9, uraian: "Electrical - Motor Voltage (R/S/T)", standar: "380-400 V" },
          { no: 10, uraian: "Electrical - Incoming Motor Current (R/S/T)", standar: "" },
          { no: 11, uraian: "Electrical - Motor load Current", standar: "" },
          { no: 12, uraian: "Electrical - Fan Motor load Current", standar: "" },
          { no: 13, uraian: "Check the Coupling", standar: "Normal" },
          { no: 14, uraian: "Check Pressure Gauge oil separator Tank", standar: "Normal" },
          { no: 15, uraian: "Check the Condensat drain (Eco Drain)", standar: "Normal" },
          { no: 16, uraian: "Ambient Temperatur", standar: "3 - 45°C" },
          { no: 17, uraian: "Discharge Temperatur", standar: "65 - 100°C" },
          { no: 18, uraian: "Running Hours Terakhir", standar: "" },
        ],
      },
      {
        id: "compressor-kaeser-4000h",
        title: "Maintenance Compressor Kaeser",
        periodeLabel: "4000 Hours",
        layout: "single",
        items: [
          { no: 1, uraian: "Cleaning Air & Oil Cooler", standar: "Bersih" },
          { no: 2, uraian: "Cleaning / Change Filter Mat", standar: "Bersih" },
          { no: 3, uraian: "Check the Leak", standar: "Tidak Bocor" },
          { no: 4, uraian: "Check the Oil Level", standar: "L/M/H" },
          { no: 5, uraian: "Change the Air Filter Cartridge", standar: "OK" },
          { no: 6, uraian: "Change the Oil Filter", standar: "OK" },
          { no: 7, uraian: "Change the Cooling Oil", standar: "OK" },
          { no: 8, uraian: "Check & Cleaning electrical panel", standar: "Bersih" },
          { no: 9, uraian: "Electrical - Motor Voltage (R/S/T)", standar: "380-400 V" },
          { no: 10, uraian: "Electrical - Incoming Motor Current (R/S/T)", standar: "" },
          { no: 11, uraian: "Electrical - Motor load Current", standar: "" },
          { no: 12, uraian: "Electrical - Fan Motor load Current", standar: "" },
          { no: 13, uraian: "Check the Coupling", standar: "Normal" },
          { no: 14, uraian: "Check Pressure Gauge oil separator Tank", standar: "Normal" },
          { no: 15, uraian: "Check the Condensat drain (Eco Drain)", standar: "Normal" },
          { no: 16, uraian: "Ambient Temperatur", standar: "3 - 45°C" },
          { no: 17, uraian: "Discharge Temperatur", standar: "65 - 100°C" },
          { no: 18, uraian: "Running Hours Terakhir", standar: "" },
        ],
      },
      {
        id: "compressor-kaeser-6000h",
        title: "Maintenance Compressor Kaeser",
        periodeLabel: "6000 Hours",
        layout: "single",
        items: [
          { no: 1, uraian: "Cleaning Air & Oil Cooler", standar: "Bersih" },
          { no: 2, uraian: "Cleaning / Change Filter Mat", standar: "Bersih" },
          { no: 3, uraian: "Check the Leak", standar: "Tidak Bocor" },
          { no: 4, uraian: "Check the Oil Level", standar: "L/M/H" },
          { no: 5, uraian: "Change the Air Filter Cartridge", standar: "OK" },
          { no: 6, uraian: "Change the Oil Filter", standar: "OK" },
          { no: 7, uraian: "Change the Separator Cartridge", standar: "OK" },
          { no: 8, uraian: "Change the Cooling Oil (FG Oil)", standar: "OK" },
          { no: 9, uraian: "Check & Cleaning electrical panel", standar: "Bersih" },
          { no: 10, uraian: "Electrical - Motor Voltage (R/S/T)", standar: "380-400 V" },
          { no: 11, uraian: "Electrical - Incoming Motor Current (R/S/T)", standar: "" },
          { no: 12, uraian: "Electrical - Motor load Current", standar: "" },
          { no: 13, uraian: "Electrical - Fan Motor load Current", standar: "" },
          { no: 14, uraian: "Check the Coupling", standar: "Normal" },
          { no: 15, uraian: "Check Pressure Gauge oil separator Tank", standar: "Normal" },
          { no: 16, uraian: "Check the Condensat drain (Eco Drain)", standar: "Normal" },
          { no: 17, uraian: "Ambient Temperatur", standar: "3 - 45°C" },
          { no: 18, uraian: "Discharge Temperatur", standar: "65 - 100°C" },
          { no: 19, uraian: "Running Hours Terakhir", standar: "" },
        ],
      },
    ],
  },
  {
    key: "genset",
    label: "Genset",
    checklists: [
      {
        id: "genset-weekly",
        title: "Maintenance Genset Caterpillar 1275 KVA",
        periodeLabel: "Weekly",
        layout: "single",
        items: [
          { no: 1, uraian: "Inspeksi", standar: "OK" },
          { no: 2, uraian: "Check level Oli", standar: "L/M/H" },
          { no: 3, uraian: "Check Level Coolant", standar: "L/M/H" },
          { no: 4, uraian: "Check Level Solar", standar: "L/M/H" },
          { no: 5, uraian: "Check Saluran udara", standar: "Bersih" },
          { no: 6, uraian: "Cleaning Filter Udara", standar: "Bersih" },
          { no: 7, uraian: "Cleaning filter Solar", standar: "Bersih" },
          { no: 8, uraian: "Check Baterai", standar: "24 Volt" },
          { no: 9, uraian: "Check Charger Baterai", standar: "24 Volt" },
          { no: 10, uraian: "Test Running", standar: "OK" },
          { no: 11, uraian: "Running Hours Terakhir", standar: "" },
        ],
      },
      {
        id: "genset-2000h",
        title: "Maintenance Genset Caterpillar 1275 KVA",
        periodeLabel: "2000 Hours",
        layout: "single",
        items: [
          { no: 1, uraian: "Check & Cleaning Cooling System (Radiator)", standar: "Bersih" },
          { no: 2, uraian: "Check the Leak", standar: "Tidak Bocor" },
          { no: 3, uraian: "Change Engine Oil", standar: "OK" },
          { no: 4, uraian: "Change Oil Filter", standar: "OK" },
          { no: 5, uraian: "Change Air Filter", standar: "OK" },
          { no: 6, uraian: "Change the Diesel Fuel Filter", standar: "OK" },
          { no: 7, uraian: "Check Radiator Hose Condition", standar: "OK" },
          { no: 8, uraian: "Check & Cleaning electrical panel", standar: "Bersih" },
          { no: 9, uraian: "Check the Electrical System Genset", standar: "OK" },
          { no: 10, uraian: "Test Running", standar: "OK" },
          { no: 11, uraian: "Running Hours Terakhir", standar: "" },
        ],
      },
      {
        id: "genset-4000h",
        title: "Maintenance Genset Caterpillar 1275 KVA",
        periodeLabel: "4000 Hours",
        layout: "single",
        items: [
          { no: 1, uraian: "Check & Cleaning Cooling System (Radiator)", standar: "Bersih" },
          { no: 2, uraian: "Check the Leak", standar: "Tidak Bocor" },
          { no: 3, uraian: "Change Engine Oil", standar: "OK" },
          { no: 4, uraian: "Change Oil Filter", standar: "OK" },
          { no: 5, uraian: "Change Air Filter", standar: "OK" },
          { no: 6, uraian: "Change the Diesel Fuel Filter", standar: "OK" },
          { no: 7, uraian: "Check Radiator Hose Condition", standar: "OK" },
          { no: 8, uraian: "Check & Cleaning electrical panel", standar: "Bersih" },
          { no: 9, uraian: "Check the Electrical System Genset", standar: "OK" },
          { no: 10, uraian: "Test Running", standar: "OK" },
          { no: 11, uraian: "Running Hours Terakhir", standar: "" },
        ],
      },
      {
        id: "genset-8000h",
        title: "Maintenance Genset Caterpillar 1275 KVA",
        periodeLabel: "8000 Hours",
        layout: "single",
        items: [
          { no: 1, uraian: "Check & Cleaning Cooling System (Radiator)", standar: "Bersih" },
          { no: 2, uraian: "Check the Leak", standar: "Tidak Bocor" },
          { no: 3, uraian: "Change Engine Oil", standar: "OK" },
          { no: 4, uraian: "Change Oil Filter", standar: "OK" },
          { no: 5, uraian: "Change Air Filter", standar: "OK" },
          { no: 6, uraian: "Change the Diesel Fuel Filter", standar: "OK" },
          { no: 7, uraian: "Check Radiator Hose Condition", standar: "OK" },
          { no: 8, uraian: "Check & Cleaning electrical panel", standar: "Bersih" },
          { no: 9, uraian: "Check the Electrical System Genset", standar: "OK" },
          { no: 10, uraian: "Test Running", standar: "OK" },
          { no: 11, uraian: "Running Hours Terakhir", standar: "" },
        ],
      },
      {
        id: "genset-monthly",
        title: "Maintenance Genset Caterpillar 1275 KVA",
        periodeLabel: "Monthly",
        layout: "monthly-grid",
        items: [
          { no: 1, uraian: "Check Level Oli", standar: "L/M/H" },
          { no: 2, uraian: "Check Level Coolant", standar: "L/M/H" },
          { no: 3, uraian: "Check Level Solar", standar: "L/M/H" },
          { no: 4, uraian: "Check Saluran Udara", standar: "Bersih" },
          { no: 5, uraian: "Cleaning Filter Udara", standar: "Bersih" },
          { no: 6, uraian: "Cleaning Filter Solar", standar: "Bersih" },
          { no: 7, uraian: "Check Baterai", standar: "24 Volt" },
          { no: 8, uraian: "Check Charger Baterai", standar: "24 Volt" },
          { no: 9, uraian: "Check Konsentrasi Coolant", standar: "OK" },
          { no: 10, uraian: "Check The Vent Belt Tension", standar: "OK" },
          { no: 11, uraian: "Check The Exhaust System", standar: "Bersih" },
        ],
      },
    ],
  },
  {
    key: "ahu",
    label: "AHU",
    checklists: [
      {
        id: "ahu-weekly",
        title: "Maintenance AHU",
        periodeLabel: "Weekly",
        layout: "single",
        items: [
          { no: 1, uraian: "Clean the Pre-filter", standar: "Clean" },
          { no: 2, uraian: "Check the Magnahelic gauge", standar: "Normal" },
          { no: 3, uraian: "Check the Bag Filter", standar: "Normal" },
          { no: 4, uraian: "Check the Condition of the Motorize Valve", standar: "Normal" },
          { no: 5, uraian: "Clean the AHU Box dan ensure it is free from dust and dirt", standar: "Clean" },
          { no: 6, uraian: "Clean the Area", standar: "Clean" },
          { no: 7, uraian: "Inspect the Unit for any Leaks", standar: "No Leak" },
        ],
      },
      {
        id: "ahu-yearly",
        title: "Maintenance AHU",
        periodeLabel: "Yearly",
        layout: "single",
        items: [
          { no: 1, uraian: "Cleaning the Pre-filter", standar: "Clean" },
          { no: 2, uraian: "Clean the Cooling Coil", standar: "Clean" },
          { no: 3, uraian: "Check the Magnahelic gauge House", standar: "No Leaks" },
          { no: 4, uraian: "Inspect the Drain Line for Leaks", standar: "No leaks" },
          { no: 5, uraian: "Inspect the Motorized Valve", standar: "Normal" },
          { no: 6, uraian: "Clean the AHU Box dan ensure it is free from dust and dirt", standar: "Clean" },
          { no: 7, uraian: "Lubricare the Motor Bearing", standar: "OK" },
          { no: 8, uraian: "Check the Condition and Tension of the blower Motor V-belt", standar: "OK" },
          { no: 9, uraian: "Clean the Blower and Impeller", standar: "Clean" },
          { no: 10, uraian: "Check the Magnahelic Gauge", standar: "Normal" },
          { no: 11, uraian: "Check and Record the Blower Motor Current (R/S/T)", standar: "Ampere" },
          { no: 12, uraian: "Check the Ducting for Leaks", standar: "No leaks" },
          { no: 13, uraian: "Check the Cooling Coil and Piping for Leaks", standar: "No leaks" },
          { no: 14, uraian: "Check and Replace the Motor Bearings", standar: "OK" },
          { no: 15, uraian: "Check and Replace the Pillow Block Bearing", standar: "OK" },
          { no: 16, uraian: "Check the Tightness of bolts and Cable Connection", standar: "Tightened" },
          { no: 17, uraian: "Check and Replace the Bag Filter", standar: "Good" },
          { no: 18, uraian: "Cek Pressure - Pre-Filter", standar: "Max. 250" },
          { no: 19, uraian: "Cek Pressure - Bag Filter", standar: "Max. 450" },
        ],
      },
      {
        id: "ahu-monthly",
        title: "Maintenance AHU",
        periodeLabel: "Monthly",
        layout: "monthly-grid",
        items: [
          { no: 1, uraian: "Clean the Pre-filter", standar: "Clean" },
          { no: 2, uraian: "Clean the Cooling Coil", standar: "Clean" },
          { no: 3, uraian: "Check the Magnahelic Gauge House", standar: "Normal" },
          { no: 4, uraian: "Inspect the Drain Line for Leaks", standar: "No Leak" },
          { no: 5, uraian: "Inspect the Motorized Valve", standar: "Normal" },
          { no: 6, uraian: "Clean the AHU Box dan ensure it is free from dust and dirt", standar: "Clean" },
          { no: 7, uraian: "Lubricate the Motor Bearing", standar: "OK" },
          { no: 8, uraian: "Check the Condition and Tension of the Blower Motor V-belt", standar: "OK" },
          { no: 9, uraian: "Clean the Blower and Impeller", standar: "Clean" },
          { no: 10, uraian: "Check the Magnahelic Gauge", standar: "Normal" },
          { no: 11, uraian: "Check and Record the Blower Motor Current (R/S/T)", standar: "Ampere" },
          { no: 12, uraian: "Check the Ducting for Leaks", standar: "No Leak" },
          { no: 13, uraian: "Check the Cooling Coil and Piping for Leaks", standar: "No Leak" },
          { no: 14, uraian: "Measure and Record the Reheat Temperature", standar: "°C" },
        ],
      },
    ],
  },
  {
    key: "boiler",
    label: "Boiler",
    checklists: [
      {
        id: "boiler-2000h",
        title: "Maintenance Boiler Miura",
        periodeLabel: "2000 Hours",
        layout: "single",
        items: [
          { no: 1, uraian: "Check the Water Quality", standar: "OK" },
          { no: 2, uraian: "Clean the Feed Water Pump Strainer", standar: "Clean" },
          { no: 3, uraian: "Clean the Air Filter", standar: "Clean" },
          { no: 4, uraian: "Inspect and Replace the Steam Packing", standar: "OK" },
          { no: 5, uraian: "Check and Clean the Nozzel Burner", standar: "Clean" },
          { no: 6, uraian: "Feed Water Pump - Check the Condition of the Mechanical Seal", standar: "Good" },
          { no: 7, uraian: "Feed Water Pump - Check the Vibration", standar: "mm/s²" },
          { no: 8, uraian: "Feed Water Pump - Check the Motor Temperatur", standar: "°C" },
          { no: 9, uraian: "Feed Water Pump - Check the Chamber", standar: "Good" },
          { no: 10, uraian: "Feed Water Pump - Check for Leaks", standar: "No Leak" },
          { no: 11, uraian: "Motor Blower - Check the Vibration", standar: "mm/s²" },
          { no: 12, uraian: "Motor Blower - Check the Motor Temperatur", standar: "°C" },
          { no: 13, uraian: "Motor Blower - Check for Leaks", standar: "No Leak" },
          { no: 14, uraian: "Clean the Electrical Panel", standar: "Clean" },
          { no: 15, uraian: "Running Hours", standar: "H" },
        ],
      },
      {
        id: "boiler-daily",
        title: "Maintenance Boiler Miura",
        periodeLabel: "Daily",
        layout: "daily-grid",
        items: [
          { no: 1, uraian: "Check for Gas Leaks", standar: "No Leaks" },
          { no: 2, uraian: "Check Exhaust Chimney Condition", standar: "OK" },
          { no: 3, uraian: "Check for Water Leaks", standar: "No Leaks" },
          { no: 4, uraian: "Check Ventilation System", standar: "OK" },
          { no: 5, uraian: "Check for Signs of Burnt Material", standar: "OK" },
          { no: 6, uraian: "Check Softener Water", standar: "OK" },
          { no: 7, uraian: "Check the Chemical Level", standar: "L/M/H" },
          { no: 8, uraian: "Inspect for Chemical Leaks", standar: "OK" },
          { no: 9, uraian: "Inspect Boiler Area", standar: "OK" },
          { no: 10, uraian: "Check the Boiler Status", standar: "Run/Off" },
          { no: 11, uraian: "Check Water Level Fluctuation", standar: "OK" },
          { no: 12, uraian: "Check the Gas Pressure", standar: "Bar" },
          { no: 13, uraian: "Check the Steam Pressure", standar: "Bar" },
          { no: 14, uraian: "Check for Odor and Noise", standar: "OK" },
          { no: 15, uraian: "Running Hours", standar: "H" },
        ],
      },
    ],
  },
  {
    key: "cooling-tower",
    label: "Cooling Tower (CT)",
    checklists: [
      {
        id: "ct-yearly",
        title: "Maintenance Cooling Tower",
        periodeLabel: "Yearly",
        layout: "single",
        items: [
          { no: 1, uraian: "Check & Replace the Rubber Coupling", standar: "OK" },
          { no: 2, uraian: "Check the Motor Vibration", standar: "Normal" },
          { no: 3, uraian: "Check the Motor Temperatur", standar: "Klas F (130°C)" },
          { no: 4, uraian: "Check the Pump Motor Voltage - R", standar: "380-400 Volt" },
          { no: 5, uraian: "Check the Pump Motor Voltage - S", standar: "380-400 Volt" },
          { no: 6, uraian: "Check the Pump Motor Voltage - T", standar: "380-400 Volt" },
          { no: 7, uraian: "Check & Clean the Strainer", standar: "Clean" },
          { no: 8, uraian: "Check for Abnormal Motor Noise", standar: "Normal" },
          { no: 9, uraian: "Check & Cleaning the Cooling Tower", standar: "Clean" },
          { no: 10, uraian: "Inspect & Replace the tower bolts as necessary", standar: "Change" },
          { no: 11, uraian: "Inspect & Replace Float Valve", standar: "Change" },
          { no: 12, uraian: "Inspect & Replace the V-belt", standar: "Change" },
          { no: 13, uraian: "Check the Gearbox Condition", standar: "No Leak" },
          { no: 14, uraian: "Greasing the Gearbox", standar: "OK" },
          { no: 15, uraian: "Check & Replace the gearbox oil", standar: "Change" },
          { no: 16, uraian: "Test Run the Motor Fan - R", standar: "380-400 Volt" },
          { no: 17, uraian: "Test Run the Motor Fan - S", standar: "380-400 Volt" },
          { no: 18, uraian: "Test Run the Motor Fan - T", standar: "380-400 Volt" },
          { no: 19, uraian: "Check the Motor Vibration (setelah test run)", standar: "Normal" },
          { no: 20, uraian: "Check the Motor Temperatur (setelah test run)", standar: "Klas F (130°C)" },
        ],
      },
      {
        id: "ct-monthly",
        title: "Maintenance Cooling Tower",
        periodeLabel: "Monthly",
        layout: "monthly-grid",
        items: [
          { no: 1, uraian: "Check & Replace the Rubber Coupling", standar: "OK" },
          { no: 2, uraian: "Check the Motor Vibration", standar: "Normal" },
          { no: 3, uraian: "Check the Motor Temperatur", standar: "Klas F (130°C)" },
          { no: 4, uraian: "Check the Motor Voltage - R", standar: "380-400 Volt" },
          { no: 5, uraian: "Check the Motor Voltage - S", standar: "380-400 Volt" },
          { no: 6, uraian: "Check the Motor Voltage - T", standar: "380-400 Volt" },
          { no: 7, uraian: "Check & Clean the Strainer", standar: "Clean" },
          { no: 8, uraian: "Check for Abnormal Motor Noise", standar: "Normal" },
          { no: 9, uraian: "Check & Cleaning the Cooling Tower", standar: "Clean" },
          { no: 10, uraian: "Inspection & Tighten the Tower Bolts as Necessary", standar: "OK" },
          { no: 11, uraian: "Check Float Valve", standar: "OK" },
          { no: 12, uraian: "Check the Condition and Tension of the Belt", standar: "OK" },
          { no: 13, uraian: "Check the Gearbox Condition", standar: "No Leak" },
          { no: 14, uraian: "Greasing the Gearbox", standar: "OK" },
        ],
      },
    ],
  },
  {
    key: "chiller",
    label: "Chiller",
    checklists: [
      {
        id: "chiller-weekly",
        title: "Maintenance Chiller",
        periodeLabel: "Weekly",
        layout: "single",
        items: [
          { no: 1, uraian: "Catatan parameter pada display unit chiller", standar: "Normal" },
          { no: 2, uraian: "Check power supply", standar: "Normal" },
          { no: 3, uraian: "Catat system operasi (pressure dan temperatur)", standar: "Normal" },
          { no: 4, uraian: "Check level refrigerant pada evaporator saat full load (10-15 menit)", standar: "Medium" },
          { no: 5, uraian: "Check fungsi thermo gauge", standar: "Normal" },
          { no: 6, uraian: "Check fungsi pressure gauge", standar: "Normal" },
          { no: 7, uraian: "Check compressor dan evaporator system", standar: "Normal" },
          { no: 8, uraian: "Check ekspansi valve", standar: "Normal" },
          { no: 9, uraian: "Check atau bersihkan Cooling Tower", standar: "Bersih" },
          { no: 10, uraian: "Cleaning Strainer", standar: "Bersih" },
        ],
      },
      {
        id: "chiller-yearly",
        title: "Maintenance Chiller",
        periodeLabel: "Yearly",
        layout: "single",
        items: [
          { no: 1, uraian: "Check Leak", standar: "Tidak Bocor" },
          { no: 2, uraian: "Check & Tightening wiring connection", standar: "Koneksi Kuat" },
          { no: 3, uraian: "Cleaning panel", standar: "Bersih" },
          { no: 4, uraian: "Check the Water Quality - PH (25°C)", standar: "6.5-8" },
          { no: 5, uraian: "Check the Water Quality - Conductivity (25°C)", standar: "< 800 μS/cm" },
          { no: 6, uraian: "Check the Water Quality - Chloride ion (Cl-)", standar: "< 200 mg(Cl-)/L" },
          { no: 7, uraian: "Check the Water Quality - Sulfate ion (SO2-)", standar: "< 200 mg(SO2-)/L" },
          { no: 8, uraian: "Check the Water Quality - Acid consumption", standar: "< 100 mg(CaCO3)/L" },
          { no: 9, uraian: "Check the Water Quality - Total Hardness", standar: "< 200 mg(CaCO3)/L" },
          { no: 10, uraian: "Check the Water Quality - Iron (Fe)", standar: "< 1.0 mg(Fe)/L" },
          { no: 11, uraian: "Check the Water Quality - Ammonium (NH+)", standar: "< 1.0 mg(NH+)/L" },
          { no: 12, uraian: "Check the Water Quality - Silica (SiO2)", standar: "< 50 mg(SiO2)/L" },
          { no: 13, uraian: "Check the water flow", standar: "OK / NG" },
          { no: 14, uraian: "Cleaning the Evaporator", standar: "Bersih" },
          { no: 15, uraian: "Cleaning the Condenser", standar: "Bersih" },
          { no: 16, uraian: "Replacement of refrigerant filter", standar: "Bersih" },
          { no: 17, uraian: "Check throttling (Ekspansi valve)", standar: "Normal" },
        ],
      },
      {
        id: "chiller-monthly",
        title: "Maintenance Chiller",
        periodeLabel: "Monthly",
        layout: "monthly-grid",
        items: [
          { no: 1, uraian: "Water Quality Analysis", standar: "Ok / NG" },
          { no: 2, uraian: "Check dan Cleaning Panel", standar: "Ok / NG" },
          { no: 3, uraian: "Electric Connection", standar: "Ok / NG" },
          { no: 4, uraian: "Leakage", standar: "Ok / NG" },
          { no: 5, uraian: "Current For - Motor (Sys 1 / Sys 2)", standar: "Ampere" },
          { no: 6, uraian: "Current For - Fan (Sys 1 / Sys 2)", standar: "Ampere" },
          { no: 7, uraian: "Temperatur - Evaporator EWT", standar: "°C" },
          { no: 8, uraian: "Temperatur - Evaporator LWT", standar: "°C" },
          { no: 9, uraian: "Temperatur - Condenser EWT", standar: "°C" },
          { no: 10, uraian: "Temperatur - Condenser LWT", standar: "°C" },
          { no: 11, uraian: "Compressor - Suction Pressure Comp 1", standar: "kPa" },
          { no: 12, uraian: "Compressor - Discharge Pressure Comp 1", standar: "kPa" },
          { no: 13, uraian: "Compressor - Suction Pressure Comp 2", standar: "kPa" },
          { no: 14, uraian: "Compressor - Discharge Pressure Comp 2", standar: "kPa" },
          { no: 15, uraian: "Cek Level Refrigerant", standar: "H / M / L" },
          { no: 16, uraian: "Cleaning Area", standar: "Yes / No" },
          { no: 17, uraian: "Star Status", standar: "Run / Stop" },
          { no: 18, uraian: "Pump - Periksa dan Ganti Rubber Coupling", standar: "Tidak Berisik" },
          { no: 19, uraian: "Pump - Periksa dan Greasing Bearing Motor", standar: "Tidak Berisik" },
          { no: 20, uraian: "Pump - Periksa dan Ganti Mechanical Seal", standar: "Tidak Bocor" },
          { no: 21, uraian: "Pump - Cleaning Strainer", standar: "Bersih" },
          { no: 22, uraian: "Pump - Current for Motor R/S/T", standar: "Sesuai Nameplate" },
        ],
      },
    ],
  },
  {
    key: "dryer",
    label: "Dryer",
    checklists: [
      {
        id: "dryer-yearly",
        title: "Maintenance Dryer",
        periodeLabel: "Yearly",
        layout: "single",
        items: [
          { no: 1, uraian: "Check the Auto Drain and Replace it if any damage is found", standar: "OK" },
          { no: 2, uraian: "Check for Air Leaks and Inspect the Refrigeration system", standar: "OK" },
          { no: 3, uraian: "Check Refrigerant Level", standar: "L/M/H" },
          { no: 4, uraian: "Replace the compress oil", standar: "Change" },
          { no: 5, uraian: "Replace the Filter Drier", standar: "Change" },
          { no: 6, uraian: "Replace the Refrigerant", standar: "Change" },
          { no: 7, uraian: "Clean the Dryer Condensor", standar: "Clean" },
          { no: 8, uraian: "Replace the filter element", standar: "OK" },
          { no: 9, uraian: "Clean the Electrical Panel", standar: "Clean" },
          { no: 10, uraian: "Test Running - Dewpoint", standar: "2-10 °C" },
          { no: 11, uraian: "Test Running - Ref. Suction Pressure", standar: "4.5-5.5 Bar" },
          { no: 12, uraian: "Test Running - Ref. Condensing Pressure", standar: "12-18 Bar" },
        ],
      },
      {
        id: "dryer-monthly",
        title: "Maintenance Dryer",
        periodeLabel: "3 Bulanan",
        layout: "monthly-grid",
        items: [
          { no: 1, uraian: "Check the Auto Drain", standar: "Normal" },
          { no: 2, uraian: "Check the Dewpoint", standar: "< 10 °C" },
          { no: 3, uraian: "Check Refrigerant Level", standar: "L/M/H" },
          { no: 4, uraian: "Check for Air Leaks and Inspect the Refrigeration System", standar: "OK" },
          { no: 5, uraian: "Clean the Dryer Condensor", standar: "Clean" },
          { no: 6, uraian: "Clean or Replace the Filter Element", standar: "OK" },
          { no: 7, uraian: "Clean the Electrical Panel", standar: "Clean" },
        ],
      },
    ],
  },
  {
    key: "pompa",
    label: "Pompa",
    checklists: [
      {
        id: "pompa-yearly",
        title: "Maintenance Pompa",
        periodeLabel: "Yearly",
        layout: "single",
        items: [
          { no: 1, uraian: "Check and Clean the Water Pump Strainer", standar: "OK" },
          { no: 2, uraian: "Check and Replace the Pump Mechanical Seal", standar: "Replace" },
          { no: 3, uraian: "Check for Leaks", standar: "No Leak" },
          { no: 4, uraian: "Check Motor Vibration", standar: "< 4.5 mm/s" },
          { no: 5, uraian: "Check the Motor Temperatur", standar: "< 100°C" },
          { no: 6, uraian: "Check the Motor Voltage - R", standar: "380-400 Volt" },
          { no: 7, uraian: "Check the Motor Voltage - S", standar: "380-400 Volt" },
          { no: 8, uraian: "Check the Motor Voltage - T", standar: "380-400 Volt" },
          { no: 9, uraian: "Check and Clean the Electrical Panel", standar: "Clean" },
          { no: 10, uraian: "Calibrate the Measuring Instruments", standar: "Good" },
        ],
      },
      {
        id: "pompa-hot-water-monthly",
        title: "Maintenance Pompa Hot Water",
        periodeLabel: "Monthly",
        layout: "monthly-grid",
        items: [
          { no: 1, uraian: "Check and Clean the Water Pump Strainer", standar: "Clean" },
          { no: 2, uraian: "Check the Pump Mechanical Seal", standar: "Good" },
          { no: 3, uraian: "Check for Leaks", standar: "No Leak" },
          { no: 4, uraian: "Check Motor Vibration", standar: "< 4.5 mm/s" },
          { no: 5, uraian: "Check the Motor Temperatur", standar: "< 100°C" },
          { no: 6, uraian: "Check the Motor Voltage - R", standar: "380-400 Volt" },
          { no: 7, uraian: "Check the Motor Voltage - S", standar: "380-400 Volt" },
          { no: 8, uraian: "Check the Motor Voltage - T", standar: "380-400 Volt" },
        ],
      },
      {
        id: "pompa-reheat-monthly",
        title: "Maintenance Pompa Reheat",
        periodeLabel: "Monthly",
        layout: "monthly-grid",
        items: [
          { no: 1, uraian: "Check and Clean the Water Pump Strainer", standar: "Clean" },
          { no: 2, uraian: "Check the Pump Mechanical Seal", standar: "Good" },
          { no: 3, uraian: "Check for Leaks", standar: "No Leak" },
          { no: 4, uraian: "Check Motor Vibration", standar: "< 4.5 mm/s" },
          { no: 5, uraian: "Check the Motor Temperatur", standar: "< 100°C" },
          { no: 6, uraian: "Check the Motor Voltage - R", standar: "380-400 Volt" },
          { no: 7, uraian: "Check the Motor Voltage - S", standar: "380-400 Volt" },
          { no: 8, uraian: "Check the Motor Voltage - T", standar: "380-400 Volt" },
        ],
      },
      {
        id: "pompa-jacket-hot-water-monthly",
        title: "Maintenance Pompa Jacket Hot Water",
        periodeLabel: "Monthly",
        layout: "monthly-grid",
        items: [
          { no: 1, uraian: "Check and Clean the Water Pump Strainer", standar: "Clean" },
          { no: 2, uraian: "Check the Pump Mechanical Seal", standar: "Good" },
          { no: 3, uraian: "Check for Leaks", standar: "No Leak" },
          { no: 4, uraian: "Check Motor Vibration", standar: "< 4.5 mm/s" },
          { no: 5, uraian: "Check the Motor Temperatur", standar: "< 100°C" },
          { no: 6, uraian: "Check the Motor Voltage - R", standar: "380-400 Volt" },
          { no: 7, uraian: "Check the Motor Voltage - S", standar: "380-400 Volt" },
          { no: 8, uraian: "Check the Motor Voltage - T", standar: "380-400 Volt" },
        ],
      },
    ],
  },
  {
    key: "wtp",
    label: "WTP",
    checklists: [
      {
        id: "wtp-yearly",
        title: "Maintenance WTP",
        periodeLabel: "Yearly",
        layout: "single",
        items: [
          { no: 1, uraian: "Check and Clean the Water Pump Strainer", standar: "Clean" },
          { no: 2, uraian: "Check and Replace the Pump Mechanical Seal", standar: "Replace" },
          { no: 3, uraian: "Check for Leaks", standar: "No Leak" },
          { no: 4, uraian: "Check Motor Vibration", standar: "< 4.5 mm/s" },
          { no: 5, uraian: "Check the Motor Temperatur", standar: "< 100°C" },
          { no: 6, uraian: "Check the Motor Voltage - R", standar: "380-400 Volt" },
          { no: 7, uraian: "Check the Motor Voltage - S", standar: "380-400 Volt" },
          { no: 8, uraian: "Check the Motor Voltage - T", standar: "380-400 Volt" },
          { no: 9, uraian: "Check and Replace the Sand Filter Media", standar: "Replace" },
          { no: 10, uraian: "Check and Clean the Electrical Panel", standar: "Clean" },
          { no: 11, uraian: "Calibrate the Measuring Instruments", standar: "Good" },
        ],
      },
      {
        id: "wtp-monthly",
        title: "Maintenance WTP",
        periodeLabel: "Monthly",
        layout: "monthly-grid",
        items: [
          { no: 1, uraian: "Check the Water Quality", standar: "OK" },
          { no: 2, uraian: "Check and Clean the Water Pump Strainer", standar: "Clean" },
          { no: 3, uraian: "Check the Pump Mechanical Seal", standar: "Good" },
          { no: 4, uraian: "Check for Leaks", standar: "No Leak" },
          { no: 5, uraian: "Check Motor Vibration", standar: "< 4.5 mm/s" },
          { no: 6, uraian: "Check the Motor Temperatur", standar: "< 100°C" },
          { no: 7, uraian: "Check the Motor Voltage - R", standar: "380-400 Volt" },
          { no: 8, uraian: "Check the Motor Voltage - S", standar: "380-400 Volt" },
          { no: 9, uraian: "Check the Motor Voltage - T", standar: "380-400 Volt" },
          { no: 10, uraian: "Backwash the Sand Filter", standar: "OK" },
        ],
      },
    ],
  },
  {
    key: "deep-well",
    label: "Deep Well (DW)",
    checklists: [
      {
        id: "dw-monthly",
        title: "Maintenance Checklist Deep Well",
        periodeLabel: "Monthly",
        layout: "monthly-grid",
        items: [
          { no: 1, uraian: "Check and Record the Flow Meter Reading", standar: "M³" },
          { no: 2, uraian: "Record the Water Flow Rate", standar: "L/sec" },
          { no: 3, uraian: "Deep Well Off Duration", standar: "Min" },
          { no: 4, uraian: "Check the Valve", standar: "5R" },
          { no: 5, uraian: "Check the Deep Well Foundation", standar: "5R" },
          { no: 6, uraian: "Water Level - SWL (Pump Off)", standar: "Meter" },
          { no: 7, uraian: "Water Level - DWL 1 (Pump On)", standar: "Meter/min" },
          { no: 8, uraian: "Water Level - DWL 2 (Pump On)", standar: "Meter/min" },
          { no: 9, uraian: "Recovery Time", standar: "Menit" },
          { no: 10, uraian: "Electrical - Current of R Phase", standar: "A" },
          { no: 11, uraian: "Electrical - Current of S Phase", standar: "A" },
          { no: 12, uraian: "Electrical - Current of T Phase", standar: "A" },
          { no: 13, uraian: "Electrical - Motor Frequency", standar: "HZ" },
        ],
      },
    ],
  },
  {
    key: "wwtp",
    label: "WWTP",
    checklists: [
      {
        id: "wwtp-aerobic-weekly",
        title: "Maintenance Aerobic Tank",
        periodeLabel: "Weekly",
        layout: "single",
        items: [
          { no: 1, uraian: "Clean the Aeration Tank Inlet Strainer", standar: "Clean" },
          { no: 2, uraian: "Check & Clean the Blower Air Filter", standar: "Clean" },
          { no: 3, uraian: "Check Blower Motor Oil Level", standar: "L/M/H" },
          { no: 4, uraian: "Check Condition and Tension of Motor Blower", standar: "OK" },
          { no: 5, uraian: "Check Aerator Membran Condition", standar: "OK" },
        ],
      },
      {
        id: "wwtp-aerobic-monthly",
        title: "Maintenance Aerobic Tank",
        periodeLabel: "Monthly",
        layout: "monthly-grid",
        items: [
          { no: 1, uraian: "Clean the Aeration Tank Inlet Strainer", standar: "Clean" },
          { no: 2, uraian: "Check & Clean the Blower Air Filter", standar: "Clean" },
          { no: 3, uraian: "Motor Blower #1 - Check Pump Vibration", standar: "mm/s" },
          { no: 4, uraian: "Motor Blower #1 - Check Pump Temperatur", standar: "°C" },
          { no: 5, uraian: "Motor Blower #1 - Inspect Pump for Leakage", standar: "No Leak" },
          { no: 6, uraian: "Motor Blower #1 - Check Oil Level", standar: "L/M/H" },
          { no: 7, uraian: "Motor Blower #2 - Check Pump Vibration", standar: "mm/s" },
          { no: 8, uraian: "Motor Blower #2 - Check Pump Temperatur", standar: "°C" },
          { no: 9, uraian: "Motor Blower #2 - Inspect Pump for Leakage", standar: "No Leak" },
          { no: 10, uraian: "Motor Blower #2 - Check Oil Level", standar: "L/M/H" },
          { no: 11, uraian: "Motor Blower #3 - Check Pump Vibration", standar: "mm/s" },
          { no: 12, uraian: "Motor Blower #3 - Check Pump Temperatur", standar: "°C" },
          { no: 13, uraian: "Motor Blower #3 - Inspect Pump for Leakage", standar: "No Leak" },
          { no: 14, uraian: "Motor Blower #3 - Check Oil Level", standar: "L/M/H" },
          { no: 15, uraian: "Check Condition and Tension of Motor Blower", standar: "OK" },
          { no: 16, uraian: "Check and Clean the Aerator Membran Condition", standar: "Clean" },
        ],
      },
      {
        id: "wwtp-anaerobic-weekly",
        title: "Maintenance Anaerobic Tank",
        periodeLabel: "Weekly",
        layout: "single",
        items: [
          { no: 1, uraian: "Cleaning the MUR Outlet Strainer", standar: "Clean" },
          { no: 2, uraian: "Clean the MUR Layer", standar: "Clean" },
          { no: 3, uraian: "Inspect the Inlet Mixer Flow Meter", standar: "M³" },
          { no: 4, uraian: "Inspect the Caustic Dosing Pump", standar: "OK" },
          { no: 5, uraian: "Inspect the Seepex MUR Pump", standar: "OK" },
          { no: 6, uraian: "Inspect the Flare Detector", standar: "OK" },
          { no: 7, uraian: "Inspect the Agitator Mixer", standar: "OK" },
          { no: 8, uraian: "Inspect the MUR Valve", standar: "No Leak" },
        ],
      },
      {
        id: "wwtp-anaerobic-monthly",
        title: "Maintenance Anaerobic Tank",
        periodeLabel: "Monthly",
        layout: "monthly-grid",
        items: [
          { no: 1, uraian: "Cleaning the MUR Outlet Strainer", standar: "Clean" },
          { no: 2, uraian: "Clean the MUR Layer", standar: "Clean" },
          { no: 3, uraian: "Inspect the Inlet Mixer Flow Meter", standar: "M³" },
          { no: 4, uraian: "Inspect the Caustic Dosing Pump - Check for Leakage", standar: "No Leak" },
          { no: 5, uraian: "Inspect the Caustic Dosing Pump - Check Dosing Pump Hose", standar: "OK" },
          { no: 6, uraian: "Inspect the Seepex MUR Pump - Check Pump Vibration", standar: "mm/s" },
          { no: 7, uraian: "Inspect the Seepex MUR Pump - Check Pump Temperatur", standar: "°C" },
          { no: 8, uraian: "Inspect the Seepex MUR Pump - Inspect Pump for Leakage", standar: "No Leak" },
          { no: 9, uraian: "Inspect the Flare Detector Function", standar: "OK" },
          { no: 10, uraian: "Inspect the Agitator Mixer - Check Pump Vibration", standar: "mm/s" },
          { no: 11, uraian: "Inspect the Agitator Mixer - Check Pump Temperatur", standar: "°C" },
          { no: 12, uraian: "Inspect the Agitator Mixer - Inspect Gearbox Condition", standar: "OK" },
          { no: 13, uraian: "Inspect the MUR Valve", standar: "No Leak" },
        ],
      },
      {
        id: "wwtp-balancing-tank-weekly",
        title: "Maintenance Balancing Tank",
        periodeLabel: "Weekly",
        layout: "single",
        items: [
          { no: 1, uraian: "Check & Cleaning Raw Waste Inlet Strainer", standar: "Clean" },
          { no: 2, uraian: "Check & Clean the Balancing Tank Outlet Filter", standar: "Clean" },
          { no: 3, uraian: "Inspect Balancing Tank Pump", standar: "OK" },
          { no: 4, uraian: "Inspect Balancing Tank Submersible Pump", standar: "OK" },
          { no: 5, uraian: "Cleaning Area Balancing Tank", standar: "5R" },
        ],
      },
      {
        id: "wwtp-balancing-tank-monthly",
        title: "Maintenance Balancing Tank",
        periodeLabel: "Monthly",
        layout: "monthly-grid",
        items: [
          { no: 1, uraian: "Check & Cleaning Raw Waste Inlet Strainer", standar: "Clean" },
          { no: 2, uraian: "Check & Clean the Balancing Tank Outlet Filter", standar: "Clean" },
          { no: 3, uraian: "Inspect Balancing Tank Pump - Check Pump Vibration", standar: "mm/s" },
          { no: 4, uraian: "Inspect Balancing Tank Pump - Check Pump Temperatur", standar: "°C" },
          { no: 5, uraian: "Inspect Balancing Tank Pump - Inspect Pump for Leakage", standar: "No Leak" },
          { no: 6, uraian: "Inspect Balancing Tank Pump - Check Mechanical Seal Condition", standar: "OK" },
          { no: 7, uraian: "Inspect Balancing Tank Submersible Pump - Check Pump Vibration", standar: "mm/s" },
          { no: 8, uraian: "Inspect Balancing Tank Submersible Pump - Check Pump Temperatur", standar: "°C" },
          { no: 9, uraian: "Inspect Balancing Tank Submersible Pump - Inspect Pump for Leakage", standar: "No Leak" },
          { no: 10, uraian: "Inspect Balancing Tank Submersible Pump - Check Mechanical Seal Condition", standar: "OK" },
          { no: 11, uraian: "Cleaning Area Balancing Tank", standar: "5R" },
        ],
      },
      {
        id: "wwtp-final-clarifier-weekly",
        title: "Maintenance Final Clarifier",
        periodeLabel: "Weekly",
        layout: "single",
        items: [
          { no: 1, uraian: "Inspect and Clean the Final Clarifier Channel", standar: "Clean" },
          { no: 2, uraian: "Inspect the Return Sludge Pump", standar: "OK" },
          { no: 3, uraian: "Check the Clarifier Agitator", standar: "OK" },
          { no: 4, uraian: "Inspect the Final Clarifier Outlet Flow Meter", standar: "M³" },
        ],
      },
      {
        id: "wwtp-final-clarifier-monthly",
        title: "Maintenance Final Clarifier",
        periodeLabel: "Monthly",
        layout: "monthly-grid",
        items: [
          { no: 1, uraian: "Inspect and Clean the Final Clarifier Channel", standar: "Clean" },
          { no: 2, uraian: "Sludge Pump #1 - Check Pump Vibration", standar: "mm/s" },
          { no: 3, uraian: "Sludge Pump #1 - Check Pump Temperatur", standar: "°C" },
          { no: 4, uraian: "Sludge Pump #1 - Inspect Pump for Leakage", standar: "No Leak" },
          { no: 5, uraian: "Sludge Pump #1 - Check the Mechanical Seal", standar: "OK" },
          { no: 6, uraian: "Sludge Pump #2 - Check Pump Vibration", standar: "mm/s" },
          { no: 7, uraian: "Sludge Pump #2 - Check Pump Temperatur", standar: "°C" },
          { no: 8, uraian: "Sludge Pump #2 - Inspect Pump for Leakage", standar: "No Leak" },
          { no: 9, uraian: "Sludge Pump #2 - Check the Mechanical Seal", standar: "OK" },
          { no: 10, uraian: "Agitator - Check Motor Vibration", standar: "mm/s" },
          { no: 11, uraian: "Agitator - Check Motor Temperatur", standar: "°C" },
          { no: 12, uraian: "Agitator - Check the Gearbox Oil", standar: "L/M/H" },
          { no: 13, uraian: "Inspect the Final Clarifier Outlet Flow Meter", standar: "M³" },
        ],
      },
    ],
  },
];

export function findChecklist(id) {
  for (const category of CHECKLIST_CATEGORIES) {
    const found = category.checklists.find((c) => c.id === id);
    if (found) return { ...found, categoryLabel: category.label };
  }
  return null;
}
