-- Seed data master: area, mesin, equipment
-- Generated dari file Excel Mesin.xlsx

do $$
declare
  v_area_id uuid;
  v_mesin_id uuid;
begin
  insert into public.area (nama) values ('BOILED CANDY (FOX''S) FILLING PACKING AREA') returning id into v_area_id;
  insert into public.mesin (area_id, nama) values (v_area_id, 'FILLING BAGGER 1') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'INCLINE CONVEYOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'WEIGHER MULTIHEAD');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'GWOLF MACHINE');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHECK WEIGHER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PACKING CONVEYOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TAPPING MACHINE BACKPACK');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'ROLLER CONVEYOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CASE WEIGHER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BAGGER 1 AREA');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CODING UNIT 1');
  insert into public.mesin (area_id, nama) values (v_area_id, 'SINGLE WRAPPER') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLOW WRAPP 4 MC');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EMPTY VACUUM 4');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR 4');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLOW WRAPP 5 MC');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EMPTY VACUUM 5');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR 5');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLOW WRAPP 6 MC');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EMPTY VACUUM 6');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR 6');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EMPTY VACUUM 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EMPTY VACUUM 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EMPTY VACUUM 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLOW WRAPP 1 MC');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLOW WRAPP 2 MC');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLOW WRAPP 3 MC');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLOW WRAPP 7 MC');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLOW WRAPP 8 MC');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLOW WRAPP 9 MC');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLOW WRAPP 10 MC');
  insert into public.mesin (area_id, nama) values (v_area_id, 'TWIST WRAPPER') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DEVIDER CONVEYOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TWIST WRAPPER AREA');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TWIST MACHINE 4');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'INCLINE CONVEYOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TWIST MACHINE 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TWIST MACHINE 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TWIST MACHINE 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MAIN CONVEYOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BLOWER');
  insert into public.mesin (area_id, nama) values (v_area_id, 'FILLING BAGGER 3') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OULET CONVEYOR 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TAPE SEALER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CASE WEIGHER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'ROLLER CONVEYOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BAGGER 3 AREA');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BUCKET ELEVATOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BLOWER 9');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MULTIHEAD WEIGHER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FILLER HEAD 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FILLER HEAD 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHECK WEIGHER 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHECK WEIGHER 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR 1');
  insert into public.mesin (area_id, nama) values (v_area_id, 'CAN SEAMER') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR (MODULAR, INDOSA)');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'WEIGHER MULTIHEAD  (YAMATO INDOSA)');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'V-FILLER  (PHLOX CAN FILL)');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TRANSFER CONVEYOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHECK WEIGHER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'INDOSA SEAMER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CODING INK JET');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TAPE SEALER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PACKING CONVEYOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SEAMING MACHINE');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FILLING & SORTING');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MAIN CONTROL PANEL');
  insert into public.mesin (area_id, nama) values (v_area_id, 'FILLING BAGGER 2') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BAGGER 2 AREA');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MIXING HOPPER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BUCKET ELEVATOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'WEIGHER MULTIHEAD');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'V-FILLER HEAD 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHECK WEIGHER 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET INCLINE CONVEYOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'V-FILLER HEAD 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHECK WEIGHER 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TAPE SEALER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CASE WEIGHER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'ROLLER CONVEYOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CODING UNIT 2');
  insert into public.mesin (area_id, nama) values (v_area_id, 'FILLING BAGGER 4') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BAGGER 4 AREA');
  insert into public.mesin (area_id, nama) values (v_area_id, 'MANUAL BULK') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SORTING');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FILLING & WEIGHTING');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SEALING');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FILLING HOPER & SORTING');
  insert into public.area (nama) values ('BOILED CANDY (FOX''S) PROCESS AREA') returning id into v_area_id;
  insert into public.mesin (area_id, nama) values (v_area_id, 'REWORK TREATMENT') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'REWORK DISOLVING TANK 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'REWORK DISOLVING TANK 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FILTER PRESS REWORK');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FILTRATION TANK');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'REWORK TANK');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'REWORK CRUSHER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'ROTARY FILTER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DICALITE DISOLVING TANK');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'VACUUM TANK');
  insert into public.mesin (area_id, nama) values (v_area_id, 'PROCESS LINE 1') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOL MIX');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOKER UNIT');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DEPOSITOR UNIT');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLING TUNNEL');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PHE 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOKER 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DEPOSITOR 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLING TUNNEL 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SAFELINE MD 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MAIN CONTROL PANEL 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RESERVOIR TANK 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RCA. INSPECTION 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FEED PUMP');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DISCHARGE PUMP');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA');
  insert into public.mesin (area_id, nama) values (v_area_id, 'TIPPING SUGAR') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Tipping Big Bag');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Tipping Small Bag');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Dissolving Tank');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Holding Tank');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Rework Tank');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SUGAR ROLLER CONVEYOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SUGAR BIG BAG');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SUGAR SMALL BAG');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COASTER BIG BAG');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PRP CHECKING STATION');
  insert into public.mesin (area_id, nama) values (v_area_id, 'PROCESS LINE 2') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOL MIX');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOKER UNIT');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DEPOSITOR UNIT');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLING TUNNEL');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PHE 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOKER 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DEPOSITOR 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLING TUNNEL 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SAFELINE MD 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MAIN CONTROL PANEL 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RESERVOIR TANK 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RCA. INSPECTION 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FEED PUMP');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DISCHARGE PUMP');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA');
  insert into public.mesin (area_id, nama) values (v_area_id, 'PROCESS LINE 3') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOL MIX');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOKER UNIT');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DEPOSITOR UNIT');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLING TUNNEL');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLMIX TANK');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLMIX AGITATOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RECERVOAR TANK');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PHE 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FEED PUMP');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DISCHARGE PUMP');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOKER 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MOVEABLE REWORK TANK');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MIXING UNIT');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DEPOSITOR 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLING TUNNEL 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SAFELINE MD');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MAIN CONTROL PANEL 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RESERVOIR TANK 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RCA. INSPECTION 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COFFEE SOLUTION DISOLVING TANK');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COFFEE SOLUTION PREPARATION TANK');
  insert into public.mesin (area_id, nama) values (v_area_id, 'PROCESS LINE 4') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AUTO FEED UNIT');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOKER UNIT');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DEPOSITOR UNIT');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLING TUNNEL');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RESERVOIR TANK');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLASH VESSEL');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FEED PUMP');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DISCHARGE PUMP 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DISCHARGE PUMP 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AUTO FEED');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PHE 4');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOKER 4');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DEPOSITOR 4');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLING TUNNEL 4');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SAFELINE MD');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MAIN CONTROL PANEL 4');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'INCORPORATOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLAVOR PUMP');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COLOR PUMP');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'REWORK TANK');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RCA. INSPECTION 4');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COLLECTING CHAMBER');
  insert into public.mesin (area_id, nama) values (v_area_id, 'FLAVOR PREPARATION') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MICROWAVE');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLAVOUR PREPARATION RACK');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EKSTRAK PREPARATION RACK');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CLEANING STATION FLAV PREP RACK');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MEJA PC');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COLOR TROLLY');
  insert into public.mesin (area_id, nama) values (v_area_id, 'GLUCOSE HANDLING') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RECEIVING GLUCOSE PUMP');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'GLUCOSE TANK 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'GLUCOSE TANK 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'GLUCOSE TRANSFER PUMP');
  insert into public.area (nama) values ('BUILDING') returning id into v_area_id;
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING GENERAL OFFICE') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Gents Toilet 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Ladies Toilet 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Server Room');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Pantry Room');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Integrity Room');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Main Office Room');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Visitor room');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Gents Toilet 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Ladies Toilet 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TERAS BUILDING');
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING CANTEEN') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA MASAK');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SUMPIT CANTEEN');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA PENYAJIAN');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA PENCUCIAN');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA MAKAN');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'GUDANG');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CUCI TANGAN LUAR KANTIN');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA BELAKANG KANTIN');
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING MUSHOLA') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA WUDHU');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA DALAM MUSHOLA');
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING CLINIC') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RUANG KLINIK');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MOTHER ROOM');
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING SECURITY GUARD') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA POS SECURITY');
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING LAUNDRY') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'POWER PANEL');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'WASHING MACHINE 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'WASHING MACHINE 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DRYER MACHINE');
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING LOCKER') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LOCKER GENTS 1 (R/F)');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LOCKER GENTS 2 (SPV)');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LADIES LOCKER 1 (SPV)');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LADIES LOCKER 2 (R/F)');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TOILET GENTS LOCKER 1 (R/F)');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TOILET GENTS LOCKER 2 (SPV)');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TOILET LADIES LOCKER 1 (SPV)');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TOILET LADIES LOCKER 2 (R/F)');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'GUDANG ISS');
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING QA') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DMAIC ROOM');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TASTING ROOM');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EXHAUST CHIMNEY');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MICROLAB ROOM');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'GENERAL LAB ROOM');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'KEEPING QUALITY ROOM');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OFFICE');
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING MICROBIOLOGY') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'POWER PANEL 10');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AUTOCLAVE');
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING PROD DRYMIX') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'POWER PANEL 11');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'INFORMTN SYSTEM 4');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SUMPIT 4');
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING PROD EXTRUSION') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'POWER PANEL 12');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'INFORMTN SYSTEM 5');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SUMPIT 5');
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING PROD TABLET') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Area BC');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Area Press');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Area AW');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'Area Packing');
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING PROD BOILED CANDY') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA PROSES');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA COOLING TUNNEL');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA WRAPPING');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA PACKING');
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING ENGINEERING') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'POWER PANEL 15');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'INFORMTN SYSTEM 8');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'UPS POWER 4');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'ENGINEERING OFFICE');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'WORKSHOP AREA');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'INDUSTRIAL SERVICE AREA');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TECHNICAL STORE');
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING WAREHOUSE RAW MATERIAL') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLROOM');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'ALLERGEN ROOM');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RACKING WAREHOUSE');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA RAW MATERIAL');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AG KITCHEN');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'ARCHIEVE ROOM');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EX BLIBLI ROOM');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LU OFFICE');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AREA BONGKAR');
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING WAREHOUSE PACKAGING MATERIAL') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'POWER PANEL 17');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'INFORMTN SYSTEM 10');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RACKING WAREHOUSE 2');
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING WAREHOUSE FINISHED GOODS') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'POWER PANEL 18');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'INFORMTN SYSTEM 11');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'RACKING WAREHOUSE 3');
  insert into public.mesin (area_id, nama) values (v_area_id, 'SINGLE WRAPPER') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EMPTY VACUUM 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLOW WRAPP 2 MC');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EMPTY VACUUM 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLOW WRAPP 3 MC');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EMPTY VACUUM 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR 3');
  insert into public.mesin (area_id, nama) values (v_area_id, 'BUILDING GUMMY-LANTAI 2') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PANEL GUMMY - LANTAI 2');
  insert into public.area (nama) values ('DRYMIX') returning id into v_area_id;
  insert into public.mesin (area_id, nama) values (v_area_id, 'DRYMIX LINE 1') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SUGAR HOPPER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MIXER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLEXIBLE SCREW');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'METAL DETECTOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FILVO FILLER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHECK WEIGHER');
  insert into public.mesin (area_id, nama) values (v_area_id, 'DRIMIX LINE 2') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MSK TIPPING');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MILO TIPPING');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MSK RECEIVING HOPPER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MILO RECEIVING HOPPER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MSK HOPPER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MILO HOPPER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SUGAR HOPPER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'WEIGHING HOPPER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MIXER RECEIVING HOPPER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PADDLE MIXER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MIXER HOPPER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PRODUCT SCREW');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'METAL DETECTOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FILLER MACHINE');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHECK WEIGHER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TAPE SEALER');
  insert into public.mesin (area_id, nama) values (v_area_id, 'PREMIX PREPARATION') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MATERIAL HANDLING');
  insert into public.area (nama) values ('EXTRUSION') returning id into v_area_id;
  insert into public.mesin (area_id, nama) values (v_area_id, 'FILLING PACKING') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'WEIGHER MULTIHEAD 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'V-FILLER 4');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CODING VIDEO JET 4');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 25');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 26');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 27');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 28');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SEALER TAPE 6');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 29');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 30');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'HOPPER 26');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'WEIGHER MULTIHEAD 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'V-FILLER 5');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CODING VIDEO JET 5');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'WEIGHER MULTIHEAD 4');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'V-FILLER 6');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CODING VIDEO JET 6');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 31');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'WEIGHER MULTIHEAD 5');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'V-FILLER 7');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CODING VIDEO JET 7');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 32');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 33');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 34');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 35');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 36');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 37');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SEALER TAPE 7');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 38');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DIE CUT FILLING 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DIE CUT FILLING 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DIE CUT');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MESIN MNP 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MESIN MNP 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MESIN MNP 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MESIN MNP 4');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MHW MILNA 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MHW MILNA 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MHW MILNA 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MHW KRIZZI 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MHW KRIZZI 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MHW KRIZZI 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MHW BUCKET ELEVATOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'POUCH FP 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'POUCH FP 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'POUCH FP 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'POUCH FP 4');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'POUCH FP 5');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'POUCH FP 6');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TAM FP 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TAM FP 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TAM FP 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TAM FP 4');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TAM FP 5');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TAM FP 6');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MAIN KONVEYOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHECKWEIGHER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PACKING MAIN KONVEYOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PSA PM');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FP AREA');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TAPPING MACHINE BESTPACK');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CASE WEIGHER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MEJA SAP');
  insert into public.mesin (area_id, nama) values (v_area_id, 'PROCESS LT.1') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'K-TRON');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'APV TANK');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'INLINE LAB PROCESS');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TUMBLER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CREAM PREPARATION TANK');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONV CRIMPER & SPREADER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DRYER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FLATTENING ROLLER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CRIMPER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLING TUNNEL');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CCP MD');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EX PROCESS AREA');
  insert into public.mesin (area_id, nama) values (v_area_id, 'PROCESS LT.2') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PSA RAW MATERIAL');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PREMIX PREPARATION');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DRYMIX MIXER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DRYMIX BUFFER TANK');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AHU STATION');
  insert into public.area (nama) values ('GUMMY CANDY') returning id into v_area_id;
  insert into public.mesin (area_id, nama) values (v_area_id, 'FILLING PACKING AREA') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MAIN CONVEYOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 1 - SHRINK MACHINE');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 1 - SPIRAL CONVEYOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - MULTI HEAD WIGHER NO. 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - MULTI HEAD WIGHER NO. 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - MULTI HEAD WIGHER NO. 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - MULTI HEAD WIGHER NO. 4');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - FILLING MACHINE NO. 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - FILLING MACHINE NO. 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - FILLING MACHINE NO. 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - FILLING MACHINE NO. 4');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - CONVEYOR TRANSFER PRODUCT');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 1 - PSA');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - TRANSPARENT POLYBAG MACHINE');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - CHECK WEIGHER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - TAPPING MACHINE BESTPACK');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - CASE WEIGHER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 2 - MEJA PC');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LOBBY LT. 2');
  insert into public.mesin (area_id, nama) values (v_area_id, 'PROCESS AREA') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - SUGAR SB342:B532TANK');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 3- BUCKET ELEVATOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 3 - METAL DETECTOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - SUGAR DISOLVING');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - PECTIN PREPARATION');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - GELATIN PREPARATION');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 -  COLOR PREPARATION');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - VITAMIN PREPARATION');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - FLAVOUR PREPARATION');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - EXTRACT PREPARATION');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - CONTIGRAV GUMMY');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - DEPOSITOR GUMMY');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - COOLING TUNNEL GUMMY');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - DEMOLDING MACHINE GUMMY');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - TUMBLER GUMMY');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - BUCKET ELEVATOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - PSA AREA');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - JELLYSTAR COOKER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - FAS DOSHING STATION');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - GLUCOSE SYRUP BUFFER TANK');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - PROCESS CLEANING STATION');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - AHU AREA');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT.4 - SLURRY TANK');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LANTAI 4 - WASHING MOLD MACHINE');
  insert into public.mesin (area_id, nama) values (v_area_id, 'DEPOSITING AREA') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MOLD TURNBACK SECTION');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MOLD EXCHANGE SECTION');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'WAITING SECTION');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AHU DEPOSITING SECTION');
  insert into public.mesin (area_id, nama) values (v_area_id, 'CCP MD LT. 3') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FILLING OVER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FILLING KONVEYOR');
  insert into public.mesin (area_id, nama) values (v_area_id, 'LOBBY LT. 3') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AHU STATION LT. 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LOBBY GUMMY LT.3');
  insert into public.mesin (area_id, nama) values (v_area_id, 'PSA AREA') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CLEANING SECTION');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AHU STATION LT. 2');
  insert into public.mesin (area_id, nama) values (v_area_id, 'FINISHED GOOD PSA') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 1 - MEJA PC');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 1 - SPIRAL KONVEYOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 1 - SORTING MACHINE');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 1 - PACKING MANUAL JAR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'LT. 1 - BESTPACK PACKING');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PSA AREA');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PSA  FG');
  insert into public.area (nama) values ('INDUSTRIAL SERVICE') returning id into v_area_id;
  insert into public.mesin (area_id, nama) values (v_area_id, 'COMPRESSED AIR') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COMPRESSOR AIR 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COMPRESSOR AIR 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COMPRESSOR AIR 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DRYER IS 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DRYER IS 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 3');
  insert into public.mesin (area_id, nama) values (v_area_id, 'PLN DISTRIBUTION') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TRAFO');
  insert into public.mesin (area_id, nama) values (v_area_id, 'GENSET GENERATION') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DAILY FUEL TANK');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FUEL PUMP');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'EXHAUST FAN');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'GENERATOR POWER 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'GENERATOR POWER 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PANEL 1');
  insert into public.mesin (area_id, nama) values (v_area_id, 'FREON R22 CHILLER GENERATION') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHILLER 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHILLER 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHILLER 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS4');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS5');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 6');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS6');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS7');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS8');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS9');
  insert into public.mesin (area_id, nama) values (v_area_id, 'AMMONIA CHILLER GENERATION') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BASIN WATER CHILLER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CIRCULATION PUMP 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CIRCULATION PUMP 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CIRCULATION PUMP 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHILLER 4');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DISTRIBUTION PUMP 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DISTRIBUTION PUMP 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DISTRIBUTION PUMP 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PANEL 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FAN EXHAUST 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FAN EXHAUST 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CHAIN HOIST');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MAIN EXHAUST FAN 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'APD EQUIPMENT');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SAFETY SHOWER');
  insert into public.mesin (area_id, nama) values (v_area_id, 'COOLING TOWER SYSTEM') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLING TOWER 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLING TOWER 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLING TOWER 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'COOLING TOWER 4');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DISTRIBUTION PUMP 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DISTRIBUTION PUMP 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DISTRIBUTION PUMP 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DISTRIBUTION PUMP 4');
  insert into public.mesin (area_id, nama) values (v_area_id, 'REHEAT SYSTEM') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS20');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS21');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PHE 8');
  insert into public.mesin (area_id, nama) values (v_area_id, 'AIR HANDLING UNIT SYSTEM') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AHU 1 (FOX''S PROCESS)');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AHU 2 (EXTRUSION FP)');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AHU 3 (EXTRUSION PROC)');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AHU 4 (FOX''S F/P)');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AHU 5 (POLO PRESS)');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AHU 6 (POLO WRAPPING)');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AHU 7 (DRYMIX)');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FAN COOLING 1 (BC)');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'FAN COOLING 2');
  insert into public.mesin (area_id, nama) values (v_area_id, 'BOILERS') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BOILER STEAM WANSON');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BURNER IS 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PIPING 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PIPING 3');
  insert into public.mesin (area_id, nama) values (v_area_id, 'CONDENSATE RETURN SYSTEM') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS22');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS23');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS24');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 7');
  insert into public.mesin (area_id, nama) values (v_area_id, 'FEED WATER SYSTEM') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 8');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS25');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS26');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS27');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS28');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS29');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 9');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS30');
  insert into public.mesin (area_id, nama) values (v_area_id, 'DRINKING WATER TREATMENT') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 10');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS31');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS32');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS33');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 11');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BASIN RESERVOIR WATER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS34');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS35');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS36');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PANEL 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS37');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS38');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS39');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PANEL 4');
  insert into public.mesin (area_id, nama) values (v_area_id, 'HOT WATER SYSTEM') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 12 (HOT WATER PRODUCT)');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS40');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS41');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PHE 9');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 13');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS42');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PHE 10');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PHE 11');
  insert into public.mesin (area_id, nama) values (v_area_id, 'WELL SYSTEM') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SUMUR 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SUMUR 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SUMUR 3');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SUMUR 4');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'SUMUR 5');
  insert into public.mesin (area_id, nama) values (v_area_id, 'AEROBIC SYSTEM TREATRMENT') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 14');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BLOWER IS 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BLOWER IS 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'DISCFUSER BUBLE');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 15');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS43');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS44');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 16');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 17');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS45');
  insert into public.mesin (area_id, nama) values (v_area_id, 'DRAINASE') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS46 (FLOOD FRONT FACT1)');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS47 (FLOOD FRONT FACT2)');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS48 (LAGOON)');
  insert into public.mesin (area_id, nama) values (v_area_id, 'INFLUENT TREATMENT') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS49');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS50');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS51');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK IS 18');
  insert into public.mesin (area_id, nama) values (v_area_id, 'ANAEROBIC SYSTEM REACTOR') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'MUR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS52');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS53');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP IS54');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BURNER IS 2');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PIPING 4');
  insert into public.area (nama) values ('PRESS CANDY (POLO)') returning id into v_area_id;
  insert into public.mesin (area_id, nama) values (v_area_id, 'LIQUOR DISSOLVING') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'AGITATOR 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'TANK 1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP PROD1');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PUMP PROD2');
  insert into public.mesin (area_id, nama) values (v_area_id, 'SUGAR PREPARATION') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'JET FILTER');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'ROTARY VALVE');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'BLOWER SYSTEM');
  insert into public.mesin (area_id, nama) values (v_area_id, 'PRESSING') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'PRESSING 1');
  insert into public.mesin (area_id, nama) values (v_area_id, 'ROLL WRAPPING 1') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CODING INK JET 1');
  insert into public.mesin (area_id, nama) values (v_area_id, 'ROLL WRAPPING 2') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CODING INK JET 2');
  insert into public.mesin (area_id, nama) values (v_area_id, 'ROLL WRAPPING 3') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'OUTLET CONVEYOR');
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CODING INK JET 3');
  insert into public.mesin (area_id, nama) values (v_area_id, 'SINGLE WRAPPING') returning id into v_mesin_id;
  insert into public.equipment (mesin_id, nama) values (v_mesin_id, 'CONVEYOR 16');
end $$;